import type { PermissionValue, RouteNameValue } from '@/shared/lib/types';

export const PermissionsNames = {
  ACTIVITY_PROFILES_SHOW_PAGE: 'ACTIVITY_PROFILES_SHOW_PAGE',

  CATALOG_EDUCATION_SHOW_MY_PROGRAMS: 'CATALOG_EDUCATION_SHOW_MY_PROGRAMS',
  CATALOG_EDUCATION_SHOW_ALL_PROGRAMS: 'CATALOG_EDUCATION_SHOW_ALL_PROGRAMS',
  CATALOG_EDUCATION_SHOW_APPLICATIONS: 'CATALOG_EDUCATION_SHOW_APPLICATIONS',
  CATALOG_EDUCATION_SHOW_APPLICATIONS_INCOMING: 'CATALOG_EDUCATION_SHOW_APPLICATIONS_INCOMING',
  CATALOG_EDUCATION_SHOW_STATISTICS: 'CATALOG_EDUCATION_SHOW_STATISTICS',

  CATALOG_EVENTS_SHOW_ALL: 'CATALOG_EVENTS_SHOW_ALL',
  CATALOG_EVENTS_SHOW_MY: 'CATALOG_EVENTS_SHOW_MY',
  CATALOG_EVENTS_SHOW_APPLICATIONS: 'CATALOG_EVENTS_SHOW_APPLICATIONS',
  CATALOG_EVENTS_SHOW_APPLICATIONS_INCOMING: 'CATALOG_EVENTS_SHOW_APPLICATIONS_INCOMING',
  CATALOG_EVENTS_SHOW_MAILINGS: 'CATALOG_EVENTS_SHOW_MAILINGS',
  CATALOG_EVENTS_SHOW_STATISTICS: 'CATALOG_EVENTS_SHOW_STATISTICS',

  CATALOG_VACANCIES_SHOW_ALL: 'CATALOG_VACANCIES_SHOW_ALL',
  CATALOG_VACANCIES_SHOW_MY: 'CATALOG_VACANCIES_SHOW_MY',
  CATALOG_VACANCIES_SHOW_APPLICATIONS: 'CATALOG_VACANCIES_SHOW_APPLICATIONS',
  CATALOG_VACANCIES_SHOW_APPLICATIONS_INCOMING: 'CATALOG_VACANCIES_SHOW_APPLICATIONS_INCOMING',
  CATALOG_VACANCIES_SPECIALISTS: 'CATALOG_VACANCIES_SPECIALISTS',
  CATALOG_VACANCIES_SHOW_STATISTICS: 'CATALOG_VACANCIES_SHOW_STATISTICS',
} as const;

type GroupedPermissionsByRoute = Partial<Record<RouteNameValue, Record<string, PermissionValue>>>;

export const GroupedPermissions = {

} as const satisfies GroupedPermissionsByRoute;
