export const RoleNames = {
  ADMIN: 'ADMIN',
  READONLY_ADMIN: 'READONLY_ADMIN',
  EDUCATION_EMPLOYEE: 'EDUCATION_EMPLOYEE',
  EVENT_EMPLOYEE: 'EVENT_EMPLOYEE',
  BAS_EMPLOYEE: 'BAS_EMPLOYEE',
  FOIV_EMPLOYEE: 'FOIV_EMPLOYEE',
  EXAM_EPLOYEE: 'EXAM_EPLOYEE',
} as const;
